### ISSUE TITLE
[meta] Wide review tracker - FPWD

### ISSUE THREAD

**Issue by xfq** [w3c/geolocation-api#43]
As a requirement for [revising a Recommendation](https://www.w3.org/2019/Process-20190301/#revised-rec) the group:

> must show that the changes to the document have received wide review

To satisfy this requirement, we use this tracker issue as an evidence that [wide review] from horizontal groups has been received.

  * Technical Architecture Group
    * [x] Review request: https://github.com/w3ctag/design-reviews/issues/529
    * [X] Feedback: https://github.com/w3ctag/design-reviews/issues/529#issuecomment-803776212
    * [X] Resolution: https://github.com/w3c/geolocation-api/pull/65  https://github.com/w3c/geolocation-api/pull/66 
  * Security
    * [x] Review request: https://lists.w3.org/Archives/Public/public-web-security/2020Jun/0001.html
    * [x] Feedback: #56
    * [X] Resolution: https://github.com/w3c/geolocation-api/pull/63
  * Privacy
    * [x] Review request: https://lists.w3.org/Archives/Public/public-privacy/2020AprJun/0027.html
    * [x] Feedback: #47 #48 #49 #54
    * [x] Resolution: Work on it at the Permissions API - https://github.com/w3c/permissions/issues/233
  * Internationalization
    * [x] Review request: https://github.com/w3c/i18n-request/issues/122
    * [x] Feedback: #50
    * [X] Resolution: https://github.com/w3c/geolocation-api/pull/51
  * Accessibility
    * [x] Review request: https://lists.w3.org/Archives/Public/public-apa/2020Jun/0015.html
    * [X] Feedback: none
    * [X] Resolution: not required. 

[wide review]: https://www.w3.org/2019/Process-20190301/#wide-review

**Comment by samuelweiler** [comment]
Unchecking the security resolution flag.  Review is complete; resolution is not.

**Comment by anssiko** [comment]
Based on this tracker we seem to have fresh enough reviews to satisfy the AB/TAG Experiment recommendation for this spec.

@marcoscaceres, as the editor, are you aware of any specific HR issues that have not been flagged in the tracker, or substantial recent changes that’d warrant re-requesting review? Please link to the relevant Permissions API issue(s) if available where the privacy feedback is discussed.

**Comment by marcoscaceres** [comment]
> @marcoscaceres, as the editor, are you aware of any specific HR issues that have not been flagged in the tracker, or substantial recent changes that’d warrant re-requesting review? 

Not at this point. No. 

> Please link to the relevant Permissions API issue(s) if available where the privacy feedback is discussed.

Relevant issue will be https://github.com/w3c/permissions/issues/233 when I pick that up. Trying to get to it.

**Comment by marcoscaceres** [comment]
Closing. Let's kick off another wide review when we transition to CR again.
